name:                aoc24
version:             0.1.0.0
github:              "arthurbacci/aoc24"
license:             Unlicense
author:              "Arthur Bacci"
maintainer:          "arthurbacci@protonmail.com"
copyright:           "Copyright (c) 2024 Arthur B. Oliveira"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/arthurbacci/aoc24#readme>

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec >= 9.5
- split
- transformers
- ilist
- extra
- criterion
- linear
- lens
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  aoc24-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc24

data-dir: data
data-files:
- data*.txt
- answer*.txt
